name: Test And Build

on:
  pull_request:
  
jobs:
  Test_and_Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Test and Lint
      - run: echo "Test and Lint"

  Validate_Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Terraform
      - run: echo "Validate Terraform"
  